# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-remote-theme
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

remote-theme: daviddarnes/alembic

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
social: # jekyll-seo-tag > social overrides
  name: Sushi Squad # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://github.com/SushiSquad7461
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Team 7461" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/orangelogo.svg" # Site logo, also used in jekyll-seo-tag
description: "FRC Team 7461 is a high school robotics team based in Redmond, Washington. Each year, we compete in the FIRST Robotics Competition, in which teams of 10 to 100 students build a robot to compete in a game that changes each year. Our team, which includes members from seven different schools, is largely student led, depending off of donations and sponsorships to continue running." # Site description and default description, also used in jekyll-seo-tag
url: "https://SushiSqud7461.Github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/SushiSquad7461/SushiSquad7461.github.io"
email: "team7461@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Sponsors
  url: /sponsors/
- title: Member Resources
  sublinks:
    - title: About FIRST
      url: https://www.firstinspires.org/robotics/frc
    - title: Safety Manual
      url: https://docs.google.com/document/d/1ReB-0HeO8rGdcyTWvBJYWyBEy8vUJQ3sLEYQ2rIfR94/edit?usp=sharing 
      title: New Member Info Form
      url: https://forms.gle/aYGh3tikR7d3vKVA8
    - title: Programming Onboarding
      url: /programming-onboarding/
    - title: 2019 Documentation
      url: https://www.chiefdelphi.com/t/team-7461-documentation-release/360456 
    - title: Kitbot on Steroids - 2020 Edition
      url: https://www.chiefdelphi.com/t/team-7461-kitbot-on-steroids-2020-edition/369079 
- title: Code Camp
  url: https://docs.google.com/forms/d/e/1FAIpQLSdlLXXRE3JCQqvBxJwFzXJ14ssN8Nnjm6jBfKWgjmmMnoe0rg/viewform?usp=sf_link 

#navigation_footer:
#- title: "See you at Worlds"
#  url: https://old.reddit.com/r/FRC/comments/bgmlpn/worlds_has_been_blessed_with_justin/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Instagram: https://instagram.com/sushisquad7461
  GitHub: https://github.com/SushiSquad7461

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
